name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment5-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Prepare host‑keys
            run: |
              sudo apt-get update && sudo apt-get -y install curl jq
              mkdir -p ~/.ssh /root/.ssh
              ssh-keygen -R github.com -f ~/.ssh/known_hosts || true
              ssh-keyscan -t rsa,ecdsa,ed25519 github.com >> ~/.ssh/known_hosts
              ssh-keygen -R github.com -f /root/.ssh/known_hosts || true
              ssh-keyscan -t rsa,ecdsa,ed25519 github.com >> /root/.ssh/known_hosts
            shell: bash
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
