name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment5-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Refresh github.com host keys   # uses only ssh‑built‑ins
            run: |
              # make sure the directory exists
              mkdir -p ~/.ssh

              # remove any stale entry – ignore the
              # “Cannot stat …/known_hosts” warning if the file is absent
              ssh-keygen -R github.com || true

              # fetch current keys (RSA, ECDSA, ED25519) straight from GitHub
              # ssh-keyscan is part of openssh‑client and **is** in the container
              ssh-keyscan -t rsa,ecdsa,ed25519 github.com >> ~/.ssh/known_hosts
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
